- name: Run Portainer CE
  hosts: all
  tasks:
    - name: Show user info
      debug:
        msg:
          - "docker_stacks_dir is {% if docker_stacks_dir is defined %}defined. Docker stacks files will be stored in {{ docker_stacks_dir }}.{% else %}not defined. Docker stacks files wil be stored in temporary dir.{% endif %}"

    - name: Check if docker is installed
      command: "which docker"
      register: docker_installed

    - name: Debug current user name
      debug:
        msg: "Current user: {{ (ansible_connection == 'local') | ternary(lookup('env','USER'), ansible_user) }}"

    - name: "Ensure current user is added to the docker group"
      user:
        name: "{{ (ansible_connection == 'local') | ternary(lookup('env','USER'), ansible_user) }}"
        groups: docker
        append: true
      become: true

    - name: Check if portainer is running
      command: "docker ps -q --filter name=portainer"
      register: portainer_running
      changed_when: false
      ignore_errors: true

    - name: Create docker stacks dir
      file:
        path: "{{ docker_stacks_dir }}"
        state: directory
      when: portainer_running.stdout == "" and docker_stacks_dir is defined

    - name: Download Portainer CE compose file
      get_url:
        url: https://downloads.portainer.io/ce2-19/portainer-agent-stack.yml
        dest: "{{ docker_stacks_dir | default('/tmp') }}/portainer-agent-stack.yml"
      when: portainer_running.stdout == ""

    - name: Replace portainer docker volume dir
      replace:
        path: "{{ docker_stacks_dir }}/portainer-agent-stack.yml"
        regexp: '/var/lib/docker/volumes:'
        replace: '{{ docker_base_dir }}/volumes:'
      when: portainer_running.stdout == "" and docker_base_dir is defined

    - name: Run portainer container
      command: "docker stack deploy -c {{ docker_stacks_dir | default('/tmp') }}/portainer-agent-stack.yml portainer"
      when: portainer_running.stdout == ""

    - name: Manual configure portainer
      ansible.builtin.fail: msg="Now you should configure portainer on https://{{ ansible_default_ipv4.address }}:9443"
      when: portainer_running.stdout == ""
