- block:
  - name: "Debug info"
    debug:
      msg: 
        - "Sending configuration for: {{ item.name }}"

  - name: Make required dirs
    shell: "mkdir -p /tmp/{{ item.name }}"

  - name: Generate QR codes
    shell: "qrencode -t png -o /tmp/{{ item.name }}/wg-qrcode.png < {{ wg_peer_conf_dir }}/client_{{ item.name }}.conf"

  - name: Copy config to tmp
    shell: "cp {{ wg_peer_conf_dir }}/client_{{ item.name }}.conf /tmp/{{ item.name }}/{{ vg_conf_name }}.conf"

  - name: Sending an email using Ansible
    mail:
      host: smtp.gmail.com
      port: 587
      username: "{{ email_login }}"
      password: "{{ email_pass }}"
      to: "{{ item.email }}"
      subject: SP6ZHP WireGuard
      body: |
        Cześć,
        
        w załączeniu znajdziesz Twoją konfigurację WireGuard.
        
        Czuwaj
        SP6ZHP
      attach:
        - "/tmp/{{ item.name }}/wg-qrcode.png"
        - "/tmp/{{ item.name }}/{{ vg_conf_name }}.conf"

  - name: Cleanup
    shell: "rm -rf /tmp/{{ item.name }}"

  - name: "Debug info"
    debug:
      msg:
        - "Configuration for {{ item.name }} sent to email: {{ item.email }}"
