- block:
  - name: "Debug info"
    debug:
      msg: 
        - "Sending configuration for: {{ item.name }}"

#  - name: Generate QR code for {{ item.name }}
#    shell: "qrencode -t ansiutf8  < {{ wg_peer_conf_dir }}/client_{{ item.name }}.conf  > {{ wg_peer_conf_dir }}/client_{{ item.name }}-qr-full"

  - name: Generate QR codes
    shell: "qrencode -t ansiutf8 < {{ wg_peer_conf_dir }}/client_{{ item.name }}.conf"
    changed_when: false
    register: qrcode

  - name: Debug QR
    debug:
      var: qrcode

  - name: Show QR codes
    debug:
      msg: "{{ item.name }}"
    loop: "{{ qrcode.lines }}"


  - name: Sending an email using Ansible
    mail:
      host: smtp.gmail.com
      port: 587
      username: "{{ email_login }}"
      password: "{{ email_pass }}"
      to: "{{ item.email }}"
      subject: SP6ZHP WireGuard
      body:
        - Cześć,
        - poniżej znajdziesz Twoją konfigurację WireGuard.
      attach:
        - "{{ wg_peer_conf_dir }}/client_{{ item.name }}.conf"


  - name: "Debug info"
    debug:
      msg:
        - "Configuration for {{ item.name }} sent to email: {{ item.email }}.."





  