- block:
  - name: "Debug info"
    debug:
      msg: 
        - "Sending configuration for: {{ item }}"

  - name: "Debug info"
    debug:
      msg:
        - "Configuration for: {{ item }} sent"





  