- name: Install Ansible Semaphore
  hosts: all
  vars:
    semaphore_stack_name: "semaphore"
    semaphore_deployed: "false"
    docker_primary_env_name: "primary"
  tasks:
    - name: Fail if semaphore_db_dir is undefined
      ansible.builtin.fail: msg="semaphore_db_dir is not defined. You should set it in playbook additional vars."
      when: semaphore_db_dir is undefined

    - name: Fail if portainer_api_key is undefined
      ansible.builtin.fail: msg="portainer_api_key is not defined. Create Portainer API key from Portainer UI and set in playbook additional vars."
      when: portainer_api_key is undefined

    - name: Fail if  is undefined
      ansible.builtin.fail: msg="semaphore_db_pass is not defined"
      when: semaphore_db_pass is undefined

    - name: Fail if semaphore_admin_pass is undefined
      ansible.builtin.fail: msg="semaphore_admin_pass is not defined"
      when: semaphore_admin_pass is undefined

    - name: Show user info
      debug:
        msg:
          - "docker_stacks_dir is {% if docker_stacks_dir is defined %}defined. Docker stacks files will be stored in {{ portainer_data_dir }}.{% else %}not defined. Docker stacks files wil be stored in temporary dir.{% endif %}"
          - "Semaphore db will be placed in {{ semaphore_db_dir }}."

    - name: Install httpie
      apt:
        pkg:
          - httpie

    - name: Get primary docker environment via portainer api
      uri:
        url: "https://127.0.0.1:9443/api/endpoints?name={{ docker_primary_env_name }}"
        method: GET
        headers:
          X-API-Key: "{{ portainer_api_key }}"
        validate_certs: false
      register: endpoints_response

#    - name: Debug endpoints_response
#      debug:
#        var: endpoints_response

    - name: Store endpoint Id
      set_fact:
        endpoint_id: "{{ endpoints_response.json[0].Id }}"

    - name: Debug endpoint_id
      debug:
        var: endpoint_id

    - name: Get Swarm ID
      shell: |
        {% raw %}
        docker info --format '{{.Swarm.Cluster.ID}}'
        {% endraw %}
      register: swarm_id_output

#    - debug:
#        var: swarm_id_output

    - name: Store Swarm Id
      set_fact:
        swarm_id: "{{ swarm_id_output.stdout }}"

    - debug:
        var: swarm_id

    - name: Get deployed stacks
      uri:
        url: "https://127.0.0.1:9443/api/stacks"
        method: GET
        headers:
          X-API-Key: "{{ portainer_api_key }}"
        validate_certs: false
      register: stacks_response

#    - name: Debug stacks_response
#      debug:
#        msg: "{{ stacks_response }}"

    - name: Search for semaphore stack
      set_fact:
        semaphore_deployed: "true"
      loop: "{{ stacks_response.json }}"
      loop_control:
        label: "{{ item.Name }}"
      when: item.Name == semaphore_stack_name

    - name: Semaphore status
      debug:
        msg: "Ansible semaphore deployed: {{ semaphore_deployed }}"

    - name: Generate access key encryption
      shell: head -c32 /dev/urandom | base64
      register: semaphore_access_key
      when: semaphore_deployed == "false"

    - name: Create semaphore db dir
      file:
        path: "{{ semaphore_db_dir }}"
        state: directory

    - name: Create docker stacks dir
      file:
        path: "{{ docker_stacks_dir  }}"
        state: directory and docker_stacks_dir is not defined

    - name: Create semaphore compose file
      template:
        src: semaphore-compose.yaml.j2
        dest: "{{ docker_stacks_dir | default('/tmp') }}/semaphore-compose.yaml"
        output_encoding: "utf-8"
      when: semaphore_deployed == "false"

    - name: Deploy semaphore stack
      shell: |
        http --verify=no --form POST https://127.0.0.1:9443/api/stacks/create/swarm/file \
        X-API-Key:"{{ portainer_api_key }}"  \
        endpointId={{ endpoint_id }} \ 
        SwarmID="{{ swarm_id }}" \
        Name="{{ semaphore_stack_name }}" \
        Env="[{\"name\": \"DB_PASS\", \"value\": \"{{ semaphore_db_pass }}\"}, {\"name\": \"SEM_ADM_PASS\", \"value\": \"{{ semaphore_admin_pass }}\"}, {\"name\": \"SEM_ENCR_KEY\", \"value\": \"{{ semaphore_access_key.stdout }}\"}]" \
        file@"{{ docker_stacks_dir | default('/tmp') }}/semaphore-compose.yaml"
      register: create_stack_response
      failed_when: "'message' in create_stack_response.stdout" #message text appears when stack is failed to deploy
      when: semaphore_deployed == "false"

