- name: Configure ansible env
  hosts: all
  tasks:
    - name: Update and upgrade all packages to the latest version
      apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 3600
