- name: Send WireGuard configuration to user
  hosts: all
  vars_files:
    - vars/wg-vars.yaml
    - ../vars/email_vault.yaml
  tasks:
    - debug:
        msg: "Sending WireGuard configuration to: {{ client_name }}"

    - name: Install required packages
      package:
        name:
          - qrencode
        state: latest

    - name: Send configuration
      include_tasks: subtasks/send-client-config.yaml
      loop: "{{ clients }}"
      loop_control:
        label: "{{ item.name }}"
      when: item.name == client_name

